/**
 * validation-schema.ts
 * Lenient Zod schemas for parsing AI-generated dossier and strategy JSON.
 * Uses .passthrough() and .optional().default() to gracefully handle
 * partial / slightly malformed AI output without throwing.
 */

import { z } from "zod";

// ─── Constants ─────────────────────────────────────────────────────────────────

export const DISCLAIMER =
  "This report is generated by an AI system for informational purposes only. " +
  "It does not constitute investment advice, legal advice, or Shariah-compliance certification. " +
  "Consult qualified legal, financial, and Shariah advisers before making investment decisions. " +
  "DaddyAI and its affiliates accept no liability for decisions made based on this report.";

// ─── Dossier Section Schema ────────────────────────────────────────────────────

const GradeEnum = z.enum(["A", "B", "C", "D", "F"]);

export const DossierSectionSchema = z
  .object({
    score: z.number().min(0).max(10).default(0),
    grade: GradeEnum.default("F"),
    headline: z.string().default(""),
    findings: z.array(z.string()).default([]),
    red_flags: z.array(z.string()).default([]),
    recommendations: z.array(z.string()).default([]),
  })
  .passthrough();

export type DossierSection = z.infer<typeof DossierSectionSchema>;

// ─── Full Dossier Schema ────────────────────────────────────────────────────────

const SECTION_KEYS = [
  "legitimacy_screen",
  "executive_summary_quality",
  "problem_solution_fit",
  "market_analysis",
  "business_model_clarity",
  "competitive_landscape",
  "go_to_market",
  "team_assessment",
  "financial_projections",
  "funding_ask",
  "risk_register",
  "traction_and_validation",
  "scalability_and_moat",
  "esg_and_ethics",
  "overall_verdict",
] as const;

type SectionKey = (typeof SECTION_KEYS)[number];

const SectionsSchema = z.object(
  Object.fromEntries(
    SECTION_KEYS.map((k) => [k, DossierSectionSchema.optional()])
  ) as Record<SectionKey, z.ZodOptional<typeof DossierSectionSchema>>
);

export const FullDossierSchema = z
  .object({
    version: z.string().default("1.0"),
    generated_at: z.string().default(() => new Date().toISOString()),
    overall_score: z.number().min(0).max(100).default(0),
    overall_grade: GradeEnum.default("F"),
    invest_signal: z
      .enum(["STRONG_YES", "CONDITIONAL_YES", "NEEDS_WORK", "NOT_READY", "REJECT"])
      .default("NOT_READY"),
    one_liner: z.string().default(""),
    sections: SectionsSchema.default({}),
    disclaimer: z.string().default(DISCLAIMER),
  })
  .passthrough();

export type FullDossier = z.infer<typeof FullDossierSchema>;

// ─── Marketing Strategy Schema ─────────────────────────────────────────────────

export const MarketingStrategySchema = z
  .object({
    version: z.string().default("1.0"),
    generated_at: z.string().default(() => new Date().toISOString()),
    target_segments: z
      .array(
        z.object({
          name: z.string(),
          description: z.string(),
          acquisition_channel: z.string(),
          estimated_cac_range: z.string().default("unknown"),
        })
      )
      .default([]),
    positioning: z
      .object({
        unique_value_proposition: z.string().default(""),
        messaging_pillars: z.array(z.string()).default([]),
        tone_of_voice: z.string().default(""),
      })
      .default({}),
    channel_mix: z
      .array(
        z.object({
          channel: z.string(),
          priority: z.enum(["HIGH", "MEDIUM", "LOW"]).default("MEDIUM"),
          rationale: z.string().default(""),
          monthly_budget_range: z.string().default(""),
          kpis: z.array(z.string()).default([]),
        })
      )
      .default([]),
    content_calendar_themes: z
      .array(
        z.object({
          week: z.number(),
          theme: z.string(),
          formats: z.array(z.string()).default([]),
        })
      )
      .default([]),
    growth_levers: z
      .array(
        z.object({
          lever: z.string(),
          description: z.string(),
          effort: z.enum(["LOW", "MEDIUM", "HIGH"]).default("MEDIUM"),
          impact: z.enum(["LOW", "MEDIUM", "HIGH"]).default("MEDIUM"),
        })
      )
      .default([]),
    ethical_guardrails: z.array(z.string()).default([]),
    disclaimer: z.string().default(
      "This marketing strategy is AI-generated for planning purposes only. Results are not guaranteed."
    ),
  })
  .passthrough();

export type MarketingStrategy = z.infer<typeof MarketingStrategySchema>;

// ─── Validate intake form ──────────────────────────────────────────────────────

export const ValidateIntakeSchema = z.object({
  planText: z.string().min(100, "Plan text must be at least 100 characters"),
  founderName: z.string().max(100).optional(),
  businessName: z.string().max(100).optional(),
  sector: z.string().max(60).optional(),
  stage: z.string().max(40).optional(),
  country: z.string().max(60).optional(),
  askAmount: z.string().max(40).optional(),
  currency: z.string().max(10).optional().default("BDT"),
  additionalContext: z.string().max(1000).optional(),
  url: z.string().url().optional(),
});

export type ValidateIntake = z.infer<typeof ValidateIntakeSchema>;

// ─── DB schemas ────────────────────────────────────────────────────────────────

export const PlanHistoryRecordSchema = z.object({
  id: z.string().uuid(),
  created_at: z.string(),
  business_name: z.string().nullable(),
  sector: z.string().nullable(),
  stage: z.string().nullable(),
  overall_score: z.number().nullable(),
  overall_grade: z.string().nullable(),
  invest_signal: z.string().nullable(),
  one_liner: z.string().nullable(),
  dossier_json: z.unknown().nullable(),
  strategy_json: z.unknown().nullable(),
  raw_plan_text: z.string().nullable(),
});

export type PlanHistoryRecord = z.infer<typeof PlanHistoryRecordSchema>;
