module.exports = {
  apps: [
    {
      name: 'daddyai',
      script: '.output/server/index.mjs',
      cwd: '/var/www/daddyai',
      env: {
        NODE_ENV: 'production',
        PORT: 3000,
        SUPABASE_URL: 'https://lcpxaoahyxdyhnkxafvf.supabase.co',
        SUPABASE_PUBLISHABLE_KEY: 'sb_publishable_Y7vlHI2hQSMcKIdpUvT98Q_3KwZtNif',
        SUPABASE_SERVICE_ROLE_KEY: 'sb_publishable_Y7vlHI2hQSMcKIdpUvT98Q_3KwZtNif',
        SUPABASE_PROJECT_ID: 'lcpxaoahyxdyhnkxafvf',
        VITE_SUPABASE_URL: 'https://lcpxaoahyxdyhnkxafvf.supabase.co',
        VITE_SUPABASE_PUBLISHABLE_KEY: 'sb_publishable_Y7vlHI2hQSMcKIdpUvT98Q_3KwZtNif',
        VITE_SUPABASE_PROJECT_ID: 'lcpxaoahyxdyhnkxafvf',
        SITE_URL: 'https://daddyai.online',
        VITE_SITE_URL: 'https://daddyai.online',
        APP_NAME: 'Daddy AI',
        APP_DOMAIN: 'daddyai.online',
        SYNC_TOKEN: 'f5e1f9b68be9fc8d69867283a6ebdf61755f23e93ff0c014def36f555d7fb42f',
        SYNC_SECRET: 'c05d89defdc77a396b6543c85bce957bb5a12394a0828c54825817d51b3cd58a',
        CRON_SECRET: 'daddyai_cron_2026_secret',
        WEBHOOK_SECRET: 'daddyai_webhook_2026_secret',
        MIMO_API_KEY: 'sk-s5he51jfvwcp0lgumatyt6mdlrd13oygx9dh3jqpzkrmvspa',
      },
      max_memory_restart: '500M',
      instances: 1,
      exec_mode: 'fork',
      watch: false,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 5000,
    },
  ],
};
