import { Button } from "@/components/ui/button";
import { Link } from "@tanstack/react-router";
import { createFileRoute } from "@tanstack/react-router";

export const Route = createFileRoute("/terms")({
  component: TermsPage,
});

function TermsPage() {
  return (
    <div className="min-h-screen bg-background p-6 md:p-24">
      <div className="max-w-3xl mx-auto glass p-8 md:p-12 rounded-[2rem]">
        <Link to="/" className="text-primary hover:underline text-sm mb-8 inline-block">← Back to Home</Link>
        <h1 className="text-4xl font-bold mb-8 italic">Terms of Service</h1>
        
        <div className="space-y-6 text-muted-foreground leading-relaxed">
          <section>
            <h2 className="text-xl font-bold text-foreground mb-3">1. Acceptance of Terms</h2>
            <p>By using Daddy AI, you agree to these terms. Our service is provided for business automation and sales training.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-foreground mb-3">2. Usage Rights</h2>
            <p>You retain all rights to the training data you upload. You grant Daddy AI a license to use this data solely to provide the services requested.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-foreground mb-3">3. Limitation of Liability</h2>
            <p>Daddy AI is a tool. We are not responsible for the specific interactions or business outcomes generated by your trained AI agents.</p>
          </section>
        </div>
      </div>
    </div>
  );
}
