/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as DataDeletionRouteImport } from './routes/data-deletion'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PrivacyRequestRouteImport } from './routes/privacy-request'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAddRouteImport } from './routes/admin.add'
import { Route as AdminApiKeysRouteImport } from './routes/admin.api-keys'
import { Route as AdminConnectionsRouteImport } from './routes/admin.connections'
import { Route as AdminLogsRouteImport } from './routes/admin.logs'
import { Route as AdminOnboardingRouteImport } from './routes/admin.onboarding'
import { Route as AdminPlaygroundRouteImport } from './routes/admin.playground'
import { Route as AdminProgressRouteImport } from './routes/admin.progress'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminSyncRouteImport } from './routes/admin.sync'
import { Route as AdminTrainingRouteImport } from './routes/admin.training'
import { Route as AdminWebhookDlqRouteImport } from './routes/admin.webhook-dlq'
import { Route as AdminWebhookTestRouteImport } from './routes/admin.webhook-test'
import { Route as ApiPublicChatRouteImport } from './routes/api/public/chat'
import { Route as ApiPublicWebhookRouteImport } from './routes/api.public.webhook'
import { Route as ApiPublicAiSyncStatusRouteImport } from './routes/api/public/ai-sync/status'
import { Route as ApiPublicCronSyncRouteImport } from './routes/api.public.cron.sync'
import { Route as ApiPublicMetaDeletionRouteImport } from './routes/api.public.meta.deletion'
import { Route as ApiPublicWebhooksMetaRouteImport } from './routes/api.public.webhooks.meta'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const DataDeletionRoute = DataDeletionRouteImport.update({
  id: '/data-deletion',
  path: '/data-deletion',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRequestRoute = PrivacyRequestRouteImport.update({
  id: '/privacy-request',
  path: '/privacy-request',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAddRoute = AdminAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApiKeysRoute = AdminApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConnectionsRoute = AdminConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOnboardingRoute = AdminOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlaygroundRoute = AdminPlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProgressRoute = AdminProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSyncRoute = AdminSyncRouteImport.update({
  id: '/sync',
  path: '/sync',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTrainingRoute = AdminTrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWebhookDlqRoute = AdminWebhookDlqRouteImport.update({
  id: '/webhook-dlq',
  path: '/webhook-dlq',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWebhookTestRoute = AdminWebhookTestRouteImport.update({
  id: '/webhook-test',
  path: '/webhook-test',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicChatRoute = ApiPublicChatRouteImport.update({
  id: '/api/public/chat',
  path: '/api/public/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhookRoute = ApiPublicWebhookRouteImport.update({
  id: '/api/public/webhook',
  path: '/api/public/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAiSyncStatusRoute = ApiPublicAiSyncStatusRouteImport.update({
  id: '/api/public/ai-sync/status',
  path: '/api/public/ai-sync/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronSyncRoute = ApiPublicCronSyncRouteImport.update({
  id: '/api/public/cron/sync',
  path: '/api/public/cron/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMetaDeletionRoute = ApiPublicMetaDeletionRouteImport.update({
  id: '/api/public/meta/deletion',
  path: '/api/public/meta/deletion',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksMetaRoute = ApiPublicWebhooksMetaRouteImport.update({
  id: '/api/public/webhooks/meta',
  path: '/api/public/webhooks/meta',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/connect': typeof ConnectRoute
  '/data-deletion': typeof DataDeletionRoute
  '/privacy': typeof PrivacyRoute
  '/privacy-request': typeof PrivacyRequestRoute
  '/terms': typeof TermsRoute
  '/admin/add': typeof AdminAddRoute
  '/admin/api-keys': typeof AdminApiKeysRoute
  '/admin/connections': typeof AdminConnectionsRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/onboarding': typeof AdminOnboardingRoute
  '/admin/playground': typeof AdminPlaygroundRoute
  '/admin/progress': typeof AdminProgressRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/sync': typeof AdminSyncRoute
  '/admin/training': typeof AdminTrainingRoute
  '/admin/webhook-dlq': typeof AdminWebhookDlqRoute
  '/admin/webhook-test': typeof AdminWebhookTestRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/chat': typeof ApiPublicChatRoute
  '/api/public/webhook': typeof ApiPublicWebhookRoute
  '/api/public/ai-sync/status': typeof ApiPublicAiSyncStatusRoute
  '/api/public/cron/sync': typeof ApiPublicCronSyncRoute
  '/api/public/meta/deletion': typeof ApiPublicMetaDeletionRoute
  '/api/public/webhooks/meta': typeof ApiPublicWebhooksMetaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/connect': typeof ConnectRoute
  '/data-deletion': typeof DataDeletionRoute
  '/privacy': typeof PrivacyRoute
  '/privacy-request': typeof PrivacyRequestRoute
  '/terms': typeof TermsRoute
  '/admin/add': typeof AdminAddRoute
  '/admin/api-keys': typeof AdminApiKeysRoute
  '/admin/connections': typeof AdminConnectionsRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/onboarding': typeof AdminOnboardingRoute
  '/admin/playground': typeof AdminPlaygroundRoute
  '/admin/progress': typeof AdminProgressRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/sync': typeof AdminSyncRoute
  '/admin/training': typeof AdminTrainingRoute
  '/admin/webhook-dlq': typeof AdminWebhookDlqRoute
  '/admin/webhook-test': typeof AdminWebhookTestRoute
  '/admin': typeof AdminIndexRoute
  '/api/public/chat': typeof ApiPublicChatRoute
  '/api/public/webhook': typeof ApiPublicWebhookRoute
  '/api/public/ai-sync/status': typeof ApiPublicAiSyncStatusRoute
  '/api/public/cron/sync': typeof ApiPublicCronSyncRoute
  '/api/public/meta/deletion': typeof ApiPublicMetaDeletionRoute
  '/api/public/webhooks/meta': typeof ApiPublicWebhooksMetaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/connect': typeof ConnectRoute
  '/data-deletion': typeof DataDeletionRoute
  '/privacy': typeof PrivacyRoute
  '/privacy-request': typeof PrivacyRequestRoute
  '/terms': typeof TermsRoute
  '/admin/add': typeof AdminAddRoute
  '/admin/api-keys': typeof AdminApiKeysRoute
  '/admin/connections': typeof AdminConnectionsRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/onboarding': typeof AdminOnboardingRoute
  '/admin/playground': typeof AdminPlaygroundRoute
  '/admin/progress': typeof AdminProgressRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/sync': typeof AdminSyncRoute
  '/admin/training': typeof AdminTrainingRoute
  '/admin/webhook-dlq': typeof AdminWebhookDlqRoute
  '/admin/webhook-test': typeof AdminWebhookTestRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/chat': typeof ApiPublicChatRoute
  '/api/public/webhook': typeof ApiPublicWebhookRoute
  '/api/public/ai-sync/status': typeof ApiPublicAiSyncStatusRoute
  '/api/public/cron/sync': typeof ApiPublicCronSyncRoute
  '/api/public/meta/deletion': typeof ApiPublicMetaDeletionRoute
  '/api/public/webhooks/meta': typeof ApiPublicWebhooksMetaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/connect'
    | '/data-deletion'
    | '/privacy'
    | '/privacy-request'
    | '/terms'
    | '/admin/add'
    | '/admin/api-keys'
    | '/admin/connections'
    | '/admin/logs'
    | '/admin/onboarding'
    | '/admin/playground'
    | '/admin/progress'
    | '/admin/settings'
    | '/admin/sync'
    | '/admin/training'
    | '/admin/webhook-dlq'
    | '/admin/webhook-test'
    | '/admin/'
    | '/api/public/chat'
    | '/api/public/webhook'
    | '/api/public/ai-sync/status'
    | '/api/public/cron/sync'
    | '/api/public/meta/deletion'
    | '/api/public/webhooks/meta'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/connect'
    | '/data-deletion'
    | '/privacy'
    | '/privacy-request'
    | '/terms'
    | '/admin/add'
    | '/admin/api-keys'
    | '/admin/connections'
    | '/admin/logs'
    | '/admin/onboarding'
    | '/admin/playground'
    | '/admin/progress'
    | '/admin/settings'
    | '/admin/sync'
    | '/admin/training'
    | '/admin/webhook-dlq'
    | '/admin/webhook-test'
    | '/admin'
    | '/api/public/chat'
    | '/api/public/webhook'
    | '/api/public/ai-sync/status'
    | '/api/public/cron/sync'
    | '/api/public/meta/deletion'
    | '/api/public/webhooks/meta'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/connect'
    | '/data-deletion'
    | '/privacy'
    | '/privacy-request'
    | '/terms'
    | '/admin/add'
    | '/admin/api-keys'
    | '/admin/connections'
    | '/admin/logs'
    | '/admin/onboarding'
    | '/admin/playground'
    | '/admin/progress'
    | '/admin/settings'
    | '/admin/sync'
    | '/admin/training'
    | '/admin/webhook-dlq'
    | '/admin/webhook-test'
    | '/admin/'
    | '/api/public/chat'
    | '/api/public/webhook'
    | '/api/public/ai-sync/status'
    | '/api/public/cron/sync'
    | '/api/public/meta/deletion'
    | '/api/public/webhooks/meta'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  ConnectRoute: typeof ConnectRoute
  DataDeletionRoute: typeof DataDeletionRoute
  PrivacyRoute: typeof PrivacyRoute
  PrivacyRequestRoute: typeof PrivacyRequestRoute
  TermsRoute: typeof TermsRoute
  ApiPublicChatRoute: typeof ApiPublicChatRoute
  ApiPublicWebhookRoute: typeof ApiPublicWebhookRoute
  ApiPublicAiSyncStatusRoute: typeof ApiPublicAiSyncStatusRoute
  ApiPublicCronSyncRoute: typeof ApiPublicCronSyncRoute
  ApiPublicMetaDeletionRoute: typeof ApiPublicMetaDeletionRoute
  ApiPublicWebhooksMetaRoute: typeof ApiPublicWebhooksMetaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-deletion': {
      id: '/data-deletion'
      path: '/data-deletion'
      fullPath: '/data-deletion'
      preLoaderRoute: typeof DataDeletionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-request': {
      id: '/privacy-request'
      path: '/privacy-request'
      fullPath: '/privacy-request'
      preLoaderRoute: typeof PrivacyRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/add': {
      id: '/admin/add'
      path: '/add'
      fullPath: '/admin/add'
      preLoaderRoute: typeof AdminAddRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/api-keys': {
      id: '/admin/api-keys'
      path: '/api-keys'
      fullPath: '/admin/api-keys'
      preLoaderRoute: typeof AdminApiKeysRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/connections': {
      id: '/admin/connections'
      path: '/connections'
      fullPath: '/admin/connections'
      preLoaderRoute: typeof AdminConnectionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/logs': {
      id: '/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/onboarding': {
      id: '/admin/onboarding'
      path: '/onboarding'
      fullPath: '/admin/onboarding'
      preLoaderRoute: typeof AdminOnboardingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/playground': {
      id: '/admin/playground'
      path: '/playground'
      fullPath: '/admin/playground'
      preLoaderRoute: typeof AdminPlaygroundRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/progress': {
      id: '/admin/progress'
      path: '/progress'
      fullPath: '/admin/progress'
      preLoaderRoute: typeof AdminProgressRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sync': {
      id: '/admin/sync'
      path: '/sync'
      fullPath: '/admin/sync'
      preLoaderRoute: typeof AdminSyncRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/training': {
      id: '/admin/training'
      path: '/training'
      fullPath: '/admin/training'
      preLoaderRoute: typeof AdminTrainingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/webhook-dlq': {
      id: '/admin/webhook-dlq'
      path: '/webhook-dlq'
      fullPath: '/admin/webhook-dlq'
      preLoaderRoute: typeof AdminWebhookDlqRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/webhook-test': {
      id: '/admin/webhook-test'
      path: '/webhook-test'
      fullPath: '/admin/webhook-test'
      preLoaderRoute: typeof AdminWebhookTestRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/chat': {
      id: '/api/public/chat'
      path: '/api/public/chat'
      fullPath: '/api/public/chat'
      preLoaderRoute: typeof ApiPublicChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhook': {
      id: '/api/public/webhook'
      path: '/api/public/webhook'
      fullPath: '/api/public/webhook'
      preLoaderRoute: typeof ApiPublicWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ai-sync/status': {
      id: '/api/public/ai-sync/status'
      path: '/api/public/ai-sync/status'
      fullPath: '/api/public/ai-sync/status'
      preLoaderRoute: typeof ApiPublicAiSyncStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/sync': {
      id: '/api/public/cron/sync'
      path: '/api/public/cron/sync'
      fullPath: '/api/public/cron/sync'
      preLoaderRoute: typeof ApiPublicCronSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/meta/deletion': {
      id: '/api/public/meta/deletion'
      path: '/api/public/meta/deletion'
      fullPath: '/api/public/meta/deletion'
      preLoaderRoute: typeof ApiPublicMetaDeletionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/meta': {
      id: '/api/public/webhooks/meta'
      path: '/api/public/webhooks/meta'
      fullPath: '/api/public/webhooks/meta'
      preLoaderRoute: typeof ApiPublicWebhooksMetaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAddRoute: typeof AdminAddRoute
  AdminApiKeysRoute: typeof AdminApiKeysRoute
  AdminConnectionsRoute: typeof AdminConnectionsRoute
  AdminLogsRoute: typeof AdminLogsRoute
  AdminOnboardingRoute: typeof AdminOnboardingRoute
  AdminPlaygroundRoute: typeof AdminPlaygroundRoute
  AdminProgressRoute: typeof AdminProgressRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSyncRoute: typeof AdminSyncRoute
  AdminTrainingRoute: typeof AdminTrainingRoute
  AdminWebhookDlqRoute: typeof AdminWebhookDlqRoute
  AdminWebhookTestRoute: typeof AdminWebhookTestRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAddRoute: AdminAddRoute,
  AdminApiKeysRoute: AdminApiKeysRoute,
  AdminConnectionsRoute: AdminConnectionsRoute,
  AdminLogsRoute: AdminLogsRoute,
  AdminOnboardingRoute: AdminOnboardingRoute,
  AdminPlaygroundRoute: AdminPlaygroundRoute,
  AdminProgressRoute: AdminProgressRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSyncRoute: AdminSyncRoute,
  AdminTrainingRoute: AdminTrainingRoute,
  AdminWebhookDlqRoute: AdminWebhookDlqRoute,
  AdminWebhookTestRoute: AdminWebhookTestRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  ConnectRoute: ConnectRoute,
  DataDeletionRoute: DataDeletionRoute,
  PrivacyRoute: PrivacyRoute,
  PrivacyRequestRoute: PrivacyRequestRoute,
  TermsRoute: TermsRoute,
  ApiPublicChatRoute: ApiPublicChatRoute,
  ApiPublicWebhookRoute: ApiPublicWebhookRoute,
  ApiPublicAiSyncStatusRoute: ApiPublicAiSyncStatusRoute,
  ApiPublicCronSyncRoute: ApiPublicCronSyncRoute,
  ApiPublicMetaDeletionRoute: ApiPublicMetaDeletionRoute,
  ApiPublicWebhooksMetaRoute: ApiPublicWebhooksMetaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
